{컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴}
{                        Next Epoch matriX User System                       }
{                                                                            }
{                              Data Structures                               }   
{                                                                            }
{                                                                            }
{ All Material Contained Herein Is Copyright 1993 Intuitive Vision Software. }
{                            All Rights Reserved.                            }
{                                                                            }
{                       Written By George A. Roberts IV                      }
{컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴}

CONST

Build:String[3]='.03';
Ver2:String[4]='0.99';

